2025-04-22 19:57:51,514 ERROR: Exception on /login [GET] [in /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/app.py", line 108, in login
    return render_template('login.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/runner/workspace/templates/login.html", line 2, in top-level template code
    {% extends 'layout.html' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/templates/layout.html", line 58, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/templates/login.html", line 6, in block 'content'
    {{ form.csrf_token }}
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/jinja2/environment.py", line 490, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'form' is undefined
2025-04-22 19:57:54,109 ERROR: Exception on /login [GET] [in /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/app.py", line 108, in login
    return render_template('login.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/runner/workspace/templates/login.html", line 2, in top-level template code
    {% extends 'layout.html' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/templates/layout.html", line 58, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/templates/login.html", line 6, in block 'content'
    {{ form.csrf_token }}
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/jinja2/environment.py", line 490, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'form' is undefined
2025-04-22 19:59:01,605 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 20:00:35,413 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 20:01:33,753 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 20:07:18,533 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 20:08:02,685 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 20:08:50,097 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 20:11:11,986 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 20:12:33,557 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 20:12:42,398 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 20:13:13,768 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 20:14:43,212 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 20:14:43,243 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 20:14:47,049 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 20:18:41,941 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 20:23:48,912 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 20:32:27,331 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 20:33:34,046 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 20:37:24,240 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 20:37:45,581 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 20:38:23,798 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 20:39:49,020 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 20:53:07,400 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 20:54:21,788 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 20:54:52,221 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 20:56:46,882 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 20:59:48,093 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 21:01:40,419 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
2025-04-22 21:01:41,862 INFO: BatchTrack startup [in /home/runner/workspace/utils/unit_utils.py:17]
